# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy via git-ftp

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftps://waws-prod-sn1-165.ftp.azurewebsites.windows.net/site/wwwroot"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
